config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  get 'searches/search'
  get 'likes/create'
  get 'likes/destroy'
  get 'create/destroy'
  get 'post_comments/new'
  get 'post_comments/create'
  get 'post_comments/edit'
  get 'post_comments/update'
  get 'post_comments/destroy'
  devise_for :users
  resources :posts do
  	resource :post_comments, only: [:create, :destroy]
  	resource :likes, only: [:create, :destroy]
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :post,counter_cache: :likes_count
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	
	belongs_to :user
	has_many :likes, dependent: :destroy
	  def like_user(user_id)
	   likes.find_by(user_id: user_id)
	  end
	has_many :taggings
	has_many :tags ,through: :taggings

	acts_as_taggable_on :skill # post.label_list が追加される
  	acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tagging
	has_many :posts ,through: :taggings
	accepts_nested_attributes_for :posts
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	has_many :posts
	has_many :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :post_comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/create_controller.rb
class CreateController < ApplicationController
  def destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
  def create
    # micropostを取得します。（before_actionをしっていたら共通化しましょう）
    @post = Post.find(params[:post_id])

    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    respond_to do |format|
        format.js
        #format.jsを追加
      end
    # 以下は多分必要ないので削除
    # @likes = Like.where(micropost_id: params[:micropost_id])
    # @microposts = Micropost.all
     @post.reload
    
  end

  def destroy
    # micropostを取得します。（before_actionをしっていたら共通化しましょう）
    @post = Post.find(params[:post_id])

    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id]).destroy
   respond_to do |format|
        
        #scaffoldにformat.jsを追加
        format.js
        #format.jsを追加
      end
      @post.reload

    # 以下は多分必要ないので削除
    # @likes = Like.where(micropost_id: params[:micropost_id])
    # @microposts = Micropost.all
  end

   private

  def set_post
    @tweet = Post.find(params[:post_id])
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.post_id = @post.id
    @comment.user_id  = current_user.id
    @comment.save
    redirect_to post_path(@post)
    
  end

  def edit
  end

  def update
  end

  def destroy
  end


    private

    def post_comment_params
      params.require(:post_comment).permit(:user_id,:post_id,:comment,)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_search
  # GET /posts
  # GET /posts.json
  
  def index
     groupings = []  # 空配列生成

    # パラメーターがあれば分割し、複数のAND条件分を生成する
    if params[:q].present?
      keywords = params[:q][:tags_name_cont].split(/[\p{blank}\s]+/)
      keywords.each { |value| groupings.push(tags_name_cont: value) }
    end

    # 生成したAND条件を検索する。初期の場合、全件出力
    @search = Post.ransack(
        combinator: 'or',
        groupings: groupings
    )
    @posts = Post.all
    # 追加
    @tags = @search.result
    # binding.pry

    @tag_ranking = Tag.all.sort_by{|p| p.taggings_count}.reverse #ランキング
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @comments = PostComment.where(post_id: @post.id)
    @Likes = Like.where(post_id: params[:id])
   

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content,:user_id,:tag_list)
    end

    def set_search
       @search = Tag.ransack(params[:q])
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
     groupings = []  # 空配列生成

    # パラメーターがあれば分割し、複数のAND条件分を生成する
    if params[:q].present?
      keywords = params[:q][:tags_name_cont].split(/[\p{blank}\s]+/)
      keywords.each { |value| groupings.push(tags_name_cont: value) }
    end

    # 生成したAND条件を検索する。初期の場合、全件出力
    @search = Post.ransack(
        combinator: 'or',
        groupings: groupings
    )
    @posts = Post.all
    # 追加
    @tags = @search.result(distinct: true)
  
  end

  def search
     groupings = []  # 空配列生成

    # パラメーターがあれば分割し、複数のAND条件分を生成する
    if params[:q].present?
      keywords = params[:q][:tag_name_cont].split(/[\p{blank}\s]+/)
      keywords.each { |value| groupings.push(tag_name_cont: value) }
    end

    # 生成したAND条件を検索する。初期の場合、全件出力
    @search = Post.ransack(
        combinator: 'or',
        groupings: groupings
    )
    @posts = Post.all
     # 追加
    @tags = @search.result
    # binding.pry
   end

   private  
  def search_params
    params.require(:q).permit(:tags_list,:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	@@markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML,
    autolink: true,
    space_after_headers: true,
    no_intra_emphasis: true,
    fenced_code_blocks: true,
    tables: true,
    hard_wrap: true,
    lax_html_blocks: true,
    strikethorough: true
 
  def markdown(text)
    @@markdown.render(text).html_safe
  end
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def markdown_editor(form, property)
    helper = ActionView::Base.new
    code = form.text_area(property, class: 'box', size: "40x20")
    code.gsub!(/">/, '" v-model="input" >') 
    code += '<div id="preview" class="box" v-html="input | marked"></div>'
    code.html_safe
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/create/destroy.html.erb
<h1>Create#destroy</h1>
<p>Find me in app/views/create/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jasmine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>  
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>  
  </head>

  <body>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="">
            <%= link_to " home",posts_path(current_user.id),class: 'glyphicon glyphicon-home' %>
          </li>
          <li class= "">
              <%#= link_to " Users",users_path, class: 'glyphicon glyphicon-user'%>
          </li>
          <li class="">
              <%#= link_to " books",books_path, class: 'glyphicon glyphicon-book'%>
          </li>
          <li class="">
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out'%>
          </li>
        <% else %>
          <li class="">
              <%= link_to " home", posts_path,class: 'glyphicon glyphicon-home'%>
          </li>
          <li class="">
              <%#= link_to " About", new_book_path, class: 'glyphicon glyphicon-link'%>
          </li>
          <li class="">
              <%#= link_to " Sign Up", new_user_registration_path, class: 'glyphicon glyphicon-edit'%>
          </li>
          <li class="">
              <%= link_to " Sign In", new_user_session_path, class: 'glyphicon glyphicon-log-in'%>
          </li>
        <% end %>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% if @post.like_user(current_user.id) %>
    <%= button_to post_likes_path(post_id: post.id), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("liked.jpg") %>
      
        
      
    <% end %>
    <%= @post.likes_count%>いいね！
  <% else %>
    <%= button_to post_likes_path(@post), id: "like-button", remote: true do %>
      <%= image_tag("like.jpg") %>
      
    <% end %>
     <%= @post.likes_count %>いいね！
  <% end %>
 
<% else %>
  <%= image_tag("like.jpg") %>
    
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/create.js.erb
$("#like<%= @post.id %>").html("<%= j(render partial: 'likes/like', locals: { post: @post}) %>")

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/destroy.js.erb
$("#like<%= @post.id %>").html("<%= j(render partial: 'likes/like', locals: { post: @post}) %>")

app/views/post_comments/destroy.html.erb
<h1>PostComments#destroy</h1>
<p>Find me in app/views/post_comments/destroy.html.erb</p>

app/views/post_comments/edit.html.erb
<h1>PostComments#edit</h1>
<p>Find me in app/views/post_comments/edit.html.erb</p>

app/views/post_comments/new.html.erb
<h1>PostComments#new</h1>
<p>Find me in app/views/post_comments/new.html.erb</p>

app/views/post_comments/update.html.erb
<h1>PostComments#update</h1>
<p>Find me in app/views/post_comments/update.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

 <div class="field" id="markdown_editor">
    <%= form.label :content %><br>
    <%= markdown_editor(form, :content) %>
  </div>

    <%= form.label :tag_list, 'タグをカンマ区切りで入力' %><br/>

    <%= text_field_tag 'post[tag_list]', @post.tag_list.join(',') %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<%= render 'searches/search' %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.user.name %></td>
        <td><%= post.tag_list %></td>
        <td><%= post.likes_count %>いいね！</td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<table>  <!-- タグランキングのテーブル -->
      <% sum = 0%>
    <% @tag_ranking.first(10).each do |rank| %>
      <td><p>第<%= sum += 1 %>位</p></td>
      <td><%= rank.name %></td>
      <% end %>
</table>


<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= markdown @post.content %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @post.tag_list %>

</p>
<span id="like<%= @post.id %>">
  <%= render partial: 'likes/like', locals: { post: @post, like: @like } %>
</span>




<%= form_for [@post,@post_comment] do |f|%>
            <div class="row">
              <div class="col-sm-12">
                <%= f.text_field :comment, rows:'20' ,cols:'5', class: "form-control",placeholder:"コメントをここに"%>
              </div>
              
            </div>
            <%= f.submit"送信する", class: "btn btn-lg btnbase-1 mt-20 pull-right" %>
<% end %>

<table>
 	<tr>
	 	<th>User名</th>
	 	<th>comment</th>
	</tr>
	<% @comments.each do |c| %>
	<tr>
		<td><%= c.user.name%></td>
		<td><%= c.comment %></td>
	</tr>
	<% end %>
 </table>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/searches/_search.html.erb
<h1>Searches#search</h1>
<p>Find me in app/views/searches/search.html.erb</p>

<%= search_form_for @search, url: searches_index_path do |f| %>
  <div class="form-group">
    <%= f.label "タグで検索" %>
    <%= f.search_field :tags_name_cont, class: "tag" %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= post.tag_list %></td>
        <td><%= post.likes_count %>いいね！</td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>